name: 'Terraform Azure Deployment'

on:
  push:
    branches:
      - main
      - feature/terraform-base
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: 'Configure Azure Credentials'
        run: |
          echo "${{ secrets.AZURE_CLIENT_ID }}" > client_id
          echo "${{ secrets.AZURE_CLIENT_SECRET }}" > client_secret
          echo "${{ secrets.AZURE_SUBSCRIPTION_ID }}" > subscription_id
          echo "${{ secrets.AZURE_TENANT_ID }}" > tenant_id

      - name: 'Terraform Init'
        run: terraform init

      - name: 'Terraform Plan'
        run: |
          terraform plan \
            -var "client_id=${{ secrets.AZURE_CLIENT_ID }}" \
            -var "client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" \
            -var "subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
            -var "tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
            -out main.tfplan
          
          cat main.tfplan



