name: Build Image Factory Runner

on:
  workflow_dispatch:
  push:

jobs:
  docker-build:
    runs-on: ubuntu-latest

    env:  
      IMAGE_NAME: "image-factory-runner"
      IMAGE_TAG: "latest"
      IMAGE_FOLDER: "images/docker/image-factory-runner"
      REGISTRY: "stovernic"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # - name: Log in to Azure Container Registry
      #   uses: azure/docker-login@v1
      #   with:
      #     login-server: ${{ secrets.REGISTRY }}
      #     username: ${{ secrets.ACR_USERNAME }}
      #     password: ${{ secrets.ACR_PASSWORD }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t $REGISTRY/$IMAGE_NAME:$IMAGE_TAG $IMAGE_FOLDER

      - name: Push Docker image
        run: |
          docker push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG
