name: Build Image Factory VM

on:
  push:
    paths:
      - ".github/workflows/packer-build-if-vm.yml"
      - "images/packer/image-factory-vm"
  workflow_dispatch:

jobs:
  packer-build:
    runs-on: ubuntu-latest

    env:  
      AZURE_LOCATION: "West Europe"
      AZURE_RESOURCE_GROUP: "wp10-silvija-rg"
      AZURE_ACG: "wp10silvijaACG"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Test jinja action
        uses: cuchi/jinja2-action@v1.2.2
        with:
          template: images/packer/image-factory-vm/values.auto.pkrvars.hcl.j2
          output_file: images/packer/image-factory-vm/test.auto.pkrvars.hcl

      - name: Test jinja action output
        run: cat images/packer/image-factory-vm/test.auto.pkrvars.hcl