name: Reusable workflow - build docker image

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      docker-dir:
        required: true
        type: string
      platform:
        required: true
        type: choice
        options:
          - amd64
          - arm64

jobs:
  docker-build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ inputs.image-name }}
      IMAGE_TAG: "${{ github.run_number }}"
      REGISTRY: ${{ secrets.REGISTRY }}
      DOCKER_DIR: ${{ inputs.docker-dir }}
      PLATFORM: ${{ inputs.platform }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          echo "Building image: $REGISTRY/$IMAGE_NAME:$IMAGE_TAG"
          docker build --platform linux/$PLATFORM -t $REGISTRY/$IMAGE_NAME:$IMAGE_TAG $DOCKER_DIR

      - name: Push Docker image
        run: |
          docker push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      - name: Setup Trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy

      - name: Check image with Trivy
        run: |
          mkdir build-artifacts
          trivy image $REGISTRY/$IMAGE_NAME:$IMAGE_TAG >> build-artifacts/vuln-scan.txt
          trivy image --format spdx ubuntu:rolling >> build-artifacts/sbom-spdx.txt
          trivy image --format cyclonedx ubuntu:rolling >> build-artifacts/sbom-cyclonedx.txt

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-artifacts
          path: build-artifacts

      - name: Tag and push Docker image as latest
        # if: github.ref == 'refs/heads/main' # TODO: uncomment once we are done with development
        run: |
          docker tag $REGISTRY/$IMAGE_NAME:$IMAGE_TAG $REGISTRY/$IMAGE_NAME:latest
          docker push $REGISTRY/$IMAGE_NAME:latest
